spring.application.name=novacart-support-platform
# Server Port Configuration
server.port=8080

# PostgreSQL Database Connection Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/novacart_db
spring.datasource.username=postgres
spring.datasource.password=Ashu@89101112
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true