server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/novacart_db
spring.datasource.username=postgres
spring.datasource.password=Ashu@89101112
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ollama Configuration (Updated to use 'llama3' which is installed locally)
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3
spring.ai.ollama.embedding.options.model=nomic-embed-text